language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - marc@axiomzen.co
    on_success: change
    on_failure: always
